### ISSUE TITLE
-1125 INVALID_LISTEN_KEY This listenKey does not exist.

### ISSUE THREAD

**Issue by numerized** [HyperCubeProject/binance-api-node#100]
Hello

all of a sudden 140 instances of my bot are showing this error, can you try to restart the socket automatically in that case?

```
(node:31075) UnhandledPromiseRejectionWarning: Error: This listenKey does not exist.
    at /root/00_boom_node/node_modules/binance-api-node/dist/http.js:47:19
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:31075) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by balthazar** [comment]
Hey

You can catch the error and detect this specific error message, call the `clean` method for each socket and restart them

**Comment by numerized** [comment]
thanks

How to catch the socket error ???

I don't have access to the .catch at then end of my catch closing function parenthesis.

**Comment by balthazar** [comment]
Good question, the websockets endpoints do not return a promise, but maybe by doing an empty one we could access the `catch` directly. I'm not able to deploy a new version right now, could you test that?

**Comment by numerized** [comment]
I'm not sure about that but I'll ask a guru friend of mine. thanks.

**Comment by balthazar** [comment]
This should be fixed in the last version
