### ISSUE TITLE
Buy Order - Error: Filter failure: LOT_SIZE

### ISSUE THREAD

**Issue by rodrigooler** [HyperCubeProject/binance-api-node#103]
When I run the code below I get an error message -> Error: Filter failure: LOT_SIZE

```js
const order = await binance(key, secret).order({
    symbol: 'ETHBTC',
    side: 'BUY',
    quantity: 0.02988799,
    type: TYPE_ORDER.MARKET
});

```
Being that I check the minimum value that is currently 0.00100000, I see no sense in this error could someone explain to me the reason and / or how to solve the problem of the error that I get in return?

**Comment by ManuCart** [comment]
Hi,
quantity is not formated as expected
see : https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule
for ETHBTC quantity should minimum 0.001 without number after the 1

**Comment by rodrigooler** [comment]
@ManuCart perfect, I'll test here and I'll give you feedback if everything works out.

**Comment by rodrigooler** [comment]
As @ManuCart  said, that's really the problem. I'll close the issue.
