### ISSUE TITLE
Minimize keep alive calls

### ISSUE THREAD

**Issue by vtrifonov** [HyperCubeProject/binance-api-node#110]
Is there a reason to call keep alive so often or the interval can be increased [here](https://github.com/HyperCubeProject/binance-api-node/blob/master/src/websocket.js#L262). I see in the documentation the it is enough to be called [once on every 30 minutes](https://github.com/binance-exchange/binance-official-api-docs/blob/master/user-data-stream.md#pingkeep-alive-a-listenkey)

**Comment by balthazar** [comment]
I believe it was previously different and required a ping more often, feel free to send a PR
