### ISSUE TITLE
depositHistory() not making network call 

### ISSUE THREAD

**Issue by blksheep93** [HyperCubeProject/binance-api-node#111]
Client2.depositHistory is not being called (with a Username and Key). I'm getting an error whenever I try to use authenticated rest points, they never get triggered on the Network tab and throw an error telling me I need a secret and a key to make authenticated calls. 

Help?

**Comment by rodrigooler** [comment]
@blksheep93 could you solve the above problem?

**Comment by blksheep93** [comment]
Nope.

**Comment by rodrigooler** [comment]
@blksheep93 did you try to follow the documentation? Here it works normal, try also to update its dependency so as not to have problems of previous versions.

```js
import Binance from 'binance-api-node'

// Authenticated client, can make signed calls
const client = Binance({
  apiKey: 'xxx',
  apiSecret: 'xxx',
})

console.log(await client.depositHistory())
```

return 

```js
{
  "depositList": [
    {
      "insertTime": 1508198532000,
      "amount": 0.04670582,
      "asset": "ETH",
      "status": 1
    }
  ],
  "success": true
}
```
