### ISSUE TITLE
performance for ws API

### ISSUE THREAD

**Issue by YoleYu** [HyperCubeProject/binance-api-node#113]
It seems that each call of websockt API will create a new ws connection, I am not sure if there is any performance issue since the establish of connection will cost sometime. If it is true, and the program needs low latency, is the HTTP api recommended ?

**Comment by tarkhil** [comment]
Quite opposite. If you need a realtime data, you create websocket once and enjoy the stream. Each REST request take time and requires a new connection.

**Comment by balthazar** [comment]
Question out-of-scope of this project.
