### ISSUE TITLE
returned object of client.order

### ISSUE THREAD

**Issue by theolangsnoer** [HyperCubeProject/binance-api-node#119]
The returned object of client.order should contains the price of the placed order. Unfortunately it doesn't. The value of the property price is null. I place limit-maker orders. I want to reuse the returned data, including the price. But as I wrote already it is null.

**Comment by rodrigooler** [comment]
Could you put the code snippet you're using and the output so I can help you?

**Comment by theolangsnoer** [comment]
Dear Rodrigo,


Please find attached to this message the code snippet. It also contains the output I got when I run this snippet. I hope this is useful for you.


Kind Regards,

Theo.

________________________________

**Comment by balthazar** [comment]
Stale issue
