### ISSUE TITLE
Catch error in buy/sell

### ISSUE THREAD

**Issue by onedayitwillmake** [HyperCubeProject/binance-api-node#12]
If an order is placed which is immediately rejected (for example, insufficient balance) - there doesn't appear to be a way to catch it? 

The returned promise results in a permanent `pending` state - even though internally something has been rejected.

I've tried to catch it every which way i could think of, but the code never makes it out that far.

For example, here's all the ways i've tried to catch the error at my level (mind the craziness, i was starting to just try everything possible)

```javascript
// Wrap whole thing in TRY/CATCH
try {
  var p = new Promise(async resolve => {
    let result = await authedClient.order(params);
    // WRAP result of .order call in TRY/CATCH
    try {
      result = await authedClient.order(params);
    } catch(e) {
      // THIS IS NEVER REACHED
      console.log("Error:", e);
    }
    resolve(result);
  })
  .catch(function(reason) {
    // THIS IS ALSO NEVER REACHED
    console.log("Error:", e);
  })
  .finally(()=>{
    // This is also never reached
    console.log("Finally")
  })
  // wrap the whole promise within a Promise.all call
  Promise.all([p]).then( () => console.log("NEVER REACHED"))

} catch(e) {
  // THIS IS NEVER REACHED
  debugger;
}

// Returned promise P is stuck in permanent `pending` state - even though internally it has failed
```

**Comment by balthazar** [comment]
Hum there's some weird things here, why do you need to create a new Promise manually if you have `await`? Let me try on my side

**Comment by balthazar** [comment]
Actually by looking at [this](https://github.com/HyperCubeProject/binance-api-node/blob/master/test/authenticated.js#L34), you can see that an API error will create a throw, thus should pass in your catch. I believe the issue resides in your implementation rather than the library's

**Comment by balthazar** [comment]
Doing the following should be enough.

```js
try {
  await authedClient.order(params)
} catch(e) {
  console.log("Error:", e)
}
```

**Comment by onedayitwillmake** [comment]
You're entirely correct, i hadn't noticed that i had a `let result = await authedClient.order(params);`, right above the try catch version of it. 

Thanks for the quick reply
