### ISSUE TITLE
order return error

### ISSUE THREAD

**Issue by ManuCart** [HyperCubeProject/binance-api-node#125]
Hi,
Sometimes I have this error
````UnhandledPromiseRejectionWarning: Error: Timestamp for this request is outside of the recvWindow.````
How to control the timestanp status ?

AND

Sometimes ````binance.order```` return error ````TOO_MANY_ORDERS````
with this code:
````
response = await binance.order({symbol: symbol,  side: side, quantity: Q, price: price.toFixed(8), recvWindow: 10000})
````
do you know if response return status : ````TOO_MANY_ORDERS````

**Comment by balthazar** [comment]
You should take a look at the binance docs and check what is the meaning of this specific status code, but it seems pretty explicit you're making too many orders in a short timeframe
