### ISSUE TITLE
Is it guaranteed that the Candles websocket will return a final ticker every time interval?

### ISSUE THREAD

**Issue by bramvbilsen** [HyperCubeProject/binance-api-node#130]
I am trying to keep track of some binance trading pairs by using the websocket candles. Whenever a minute passes, I would like to push a new candle to my array of candles. I am currently doing this by looking at the `isFinal` property of the returned candle, my code looks something like this:
```js
binance.ws.candles("BTCUSDT", "1m", candle => {
  if (candle.isFinal) {
      allCandles.push(candle);
  } else {
      allCandles[allCandles.length-1] = candle;
  }
});
```
This code would only work of course if it is guaranteed that for every time interval (every minute here) I get one candle with `isFinal = true`.  
So my question is: Is this guaranteed? Can I be certain that I will get one candle per time interval with `isFinal = true`?

**Comment by ManuCart** [comment]
Hi, yes it's should be. Never verified at every interval but work for me.
The only thing is the delay. It's comes only when a transaction is doing after the period.

**Comment by bramvbilsen** [comment]
@ManuCart Well, the delay is inevitable I guess so that's no problem.
Thanks for your fast response!
