### ISSUE TITLE
Where are Kline start and close times?

### ISSUE THREAD

**Issue by MaxSvargal** [HyperCubeProject/binance-api-node#14]
Why "Kline start time" and "Kline close time" are not isset in candles ws stream responds?
docs ref: https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#klinecandlestick-streams

**Comment by balthazar** [comment]
Because they changed their API, it's difficult to keep track without getting notified 🙂

**Comment by MaxSvargal** [comment]
Ok, let's fix it?

**Comment by balthazar** [comment]
Oh sorry I didn't in less than 30 seconds? I'm not you personal developer, you should remember that. If you're really in a hurry, a PR can be done pretty quickly.

**Comment by MaxSvargal** [comment]
I'm already complete a fix, but you was faster =)
Also check tests plz
https://github.com/MaxSvargal/binance-api-node/commit/e64fe4057d07bb75da99aa5eeebdce9d75fc6fcc

**Comment by balthazar** [comment]
Probably don't want to check`lastTrade` and `firstTrade` here actually, since it might be null. I'll keep it like this, but thanks for the input.
