### ISSUE TITLE
Get servertime with client.book()

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [HyperCubeProject/binance-api-node#140]
On all websocket streams we get a so called "eventTime", yet why do other requests not return this value? 

Is it possible to get the Time from that response? 

Do you think that this would be accurate as a workaround? 

```
let book = async () => {
  console.log(await client.time())
  console.log(await client.book({ symbol: 'ETHBTC' }))
};book();
```

**Comment by balthazar** [comment]
You're not using the return value of `client.time()` here so not sure what you'd like to achieve, but yes because the http methods don't return a time you would need to call it on your own if you want to use it

**Comment by hp8wvvvgnj6asjm7** [comment]
Also if one of the calls delay, the time would be wrong anyways... It already is, by milliseconds.

**Comment by hp8wvvvgnj6asjm7** [comment]
You mean this by return value? : 

return {
    ping: () => publicCall('/v1/ping').then(() => true),
    time: () => publicCall('/v1/time').then(r => r.serverTime),
    exchangeInfo: () => publicCall('/v1/exchangeInfo'),

    book,

**Comment by balthazar** [comment]
You snippet of code doesn't use the return value of `time` beside printing it, not sure what to say

**Comment by hp8wvvvgnj6asjm7** [comment]
Oh, no real use case right now, just a test.
