### ISSUE TITLE
@0ms compression option for websockets

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [HyperCubeProject/binance-api-node#142]
Feature request:

> 
> 
> Ninj0r admin, [Oct 20, 2017, 10:04:53 AM]:
> Yeah. You can use somethng like wss://stream.binance.com:9443/ws/ethbtc@depth20 as a backup to ensure you always have the most accurate best 20 levels.
> 
> Also note, that you can add @0ms to the end of a depth stream
> 
> For example:
> wss://stream.binance.com:9443/ws/ethbtc@depth20@0ms
> wss://stream.binance.com:9443/ws/ethbtc@depth@0ms
> 
> This will give you uncompressed updates. The default streams send out updates every second (this is why there is U and u)
> 
> the @0ms stream will send out every update as it is received (this payload will have no U)
> 
> But it will be a firehosee of data, and it has lockedup/crashed some UIs. This is why the default has 1000ms update compression.
> 

--

>  **start_ticker_socket(callback, update_time=WEBSOCKET_UPDATE_1SECOND)
> 
>     Start a websocket for ticker data
> 
>     By default all markets are included in an array.
> 
>     Using a 0ms update time will split markets into separate messages.
>     Parameters:	
> 
>         callback (function) – callback function to handle messages
>         update_time (enum) – Update time interval, default WEBSOCKET_UPDATE_1SECOND
> 
>     Returns:	
> 
>     connection key string if successful, False otherwise**

**Comment by balthazar** [comment]
We construct websocket urls like [this](https://github.com/HyperCubeProject/binance-api-node/blob/master/src/websocket.js#L10), since it appears to be a new parameter we do not support it yet

**Comment by laurijamsa** [comment]
Actually, it's not a new parameter. It's discontinued by Binance over a year ago.

https://github.com/sammchardy/python-binance/issues/38

**Comment by balthazar** [comment]
Thanks for the info @laurijamsa, closing
