### ISSUE TITLE
How to close binance.ws.candles socket

### ISSUE THREAD

**Issue by ManuCart** [HyperCubeProject/binance-api-node#151]
Hi, I need to close some socket after a while, but don't know how to do this.
Someone Know?

**Comment by wanderer2** [comment]
As per the docs.

**WebSockets**
Every websocket utility returns a function you can call to close the opened connection and avoid memory issues.

`const clean = client.ws.depth('ETHBTC', depth => {
  console.log(depth)
})
 
// After you're done
clean()`

I loaded an array strms[ ] with several streams.  When a condition is met, I 1st close the stream

`strms[i]()`

then I remove it from the array `strms.splice(i, 1)`  You can close a stream with calling name ()### ###

**Comment by ManuCart** [comment]
Hi Raymond,

Thanks for your explanation, never think about that.
I hope this help

**Comment by Sicklou** [comment]
Sorry to reopen this thread but I put the return of the call `client.ws.user` in an array, but when I looked at it, it says thats its a Promise and not a function, so how can I close the connection ?

**Comment by ManuCart** [comment]
Salut,
I had this error, when I forgot the await
use this : 
```
ws_user = await binance.ws.user(...)
```
and later to close websocket
```
ws_user()
```
