### ISSUE TITLE
Exchange Info Endpoint

### ISSUE THREAD

**Issue by nmsz97** [HyperCubeProject/binance-api-node#16]
Hi,

Can we get support for `/api/v1/exchangeInfo` endpoint that provides information about the LOT_SIZE and other exchange info on every pair.

Thanks

**Comment by wannesdemaeght** [comment]
request("https://api.binance.com/api/v1/exchangeInfo", function (error, body, data) {
		var array = JSON.parse(data).symbols
		for (i in array) {
			for (x = 1; x < NumberOfAlts+1; x++) {
				if (array[i].symbol == Market.Binance[x]) {
					Decimal.Amount.Binance[x]	= -Math.log10(array[i].filters[1].stepSize)
					Decimal.Price.Binance[x] 	= -Math.log10(array[i].filters[0].tickSize)
				}
			}
		}
	})

**Comment by balthazar** [comment]
The `exchangeInfo` is now availble in the library @wannesdemaeght 🙂

**Comment by wannesdemaeght** [comment]
haha, my bad :-)
