### ISSUE TITLE
How to close binance.ws

### ISSUE THREAD

**Issue by ManuCart** [HyperCubeProject/binance-api-node#171]
Hello,

I would like to close a websocket when my internet connection is down.
I check every 5 minutes my connection with ping and close websocket if it's down. 
How to do this?
My code :
````
function tests(symbols){
websocket = binance.ws.candles(symbols, '30m', candle => {
  log(candle)
 })
}
````
Because when my connection up again the websocket not work anymore.

**Comment by balthazar** [comment]
https://github.com/HyperCubeProject/binance-api-node#websockets

**Comment by ManuCart** [comment]
Hi @balthazar, my bad
Thanks for your great work

**Comment by balthazar** [comment]
@ManuCart ❤️
