### ISSUE TITLE
.npmignore not ignoring .git folder

### ISSUE THREAD

**Issue by shadow1349** [HyperCubeProject/binance-api-node#177]
Since you don't seem to have a .npmignore on this repo the .git folder is not being ignored. This is causing errors like this:

```
npm ERR! path /Users/username/Documents/Workspace/Folder/project/node_modules/binance-api-node
npm ERR! code EISGIT
npm ERR! git /Users/username/Documents/Workspace/Folder/project/node_modules/binance-api-node: Appears to be a git repo or submodule.
npm ERR! git /Users/username/Documents/Workspace/Folder/project/node_modules/binance-api-node
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

This happens every time I try to npm install a new package or version.

If you simply add a .npmignore file containing the following:

```
src
test
.babelrc
.eslintrc
.git
.gitignore
.travis.yml
yarn.lock
```

It will also help reduce your package size by not transporting things like src and test so only lib and index.d.ts

**Comment by jsappme** [comment]
same issue here

**Comment by balthazar** [comment]
`0.9.2`
