### ISSUE TITLE
Illegal characters found in parameter 'price'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$

### ISSUE THREAD

**Issue by ansarimaaz21** [HyperCubeProject/binance-api-node#181]
Illegal characters found in parameter 'price'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$

When Creating order for NPXSBTC at price of 0.0000001 ?

**Comment by balthazar** [comment]
Are you sure you are using a string?
