### ISSUE TITLE
Unknown Processing Error

### ISSUE THREAD

**Issue by nmsz97** [HyperCubeProject/binance-api-node#20]
Getting this error but not sure where from:

```
error: Unhandled Rejection at: Promise  Promise {
  <rejected> Error: An unknown error occured while processing the request.
    at /home/jafri/binance-api/node_modules/binance-api-node/dist/http.js:47:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) } Error: An unknown error occured while processing the request.
    at /home/jafri/binance-api/node_modules/binance-api-node/dist/http.js:47:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

**Comment by balthazar** [comment]
Seems like an API error, can I see your call?

**Comment by forma-exacta** [comment]
I received the same error while trying to open the user data websocket. The userDataStream endpoint (https://api.binance.com/api/v1/userDataStream) is producing a 500 error with this response:
```
{
    "code": -1000,
    "msg": "An unknown error occured while processing the request."
}
```

Is there something wrong with this endpoint? The X-MBX-APIKEY is being sent, so it's not an auth error.

**Comment by nmsz97** [comment]
Yes the user data websocket is throwing that error.

**Comment by balthazar** [comment]
Not much I can do on my side then if the endpoint itself is not behaving as expected 🙁

**Comment by forma-exacta** [comment]
Yeah, it's an issue on Binance's side. I opened a support ticket with them. We'll see if that produces anything. Thanks for responding.

**Comment by balthazar** [comment]
Cool!
