### ISSUE TITLE
Type definitions

### ISSUE THREAD

**Issue by bennyn** [HyperCubeProject/binance-api-node#21]
Hi @balthazar, I am a big fan of your Binance API. It's really easy to handle and I like that it uses Promises. 

The only thing which I am missing so far are type definitions for TypeScript. I would therefore like to create TypeScript definitions for this library and contribute them in various Pull Request (one for each section). But before I start with it I would like to know if you think that it is a good thing to do? 

Best,
Benny

**Comment by balthazar** [comment]
Hello Ben, thanks!

I've mixed feelings about JS typings to be honest, but I know some people grew to like it. What would it imply in term of configuration in this repository exactly? I would prefer if we kept it as simple as possible (all the babel thing is already a tad big imho), but is that even possible to separate typings and the repo source?

**Comment by bennyn** [comment]
It doesn't require much. In order to serve typings together with your module, you just need to do two simple steps.

1. Add an `index.d.ts` file (with all the type definitions) to the repository 
1. Reference the `index.d.ts` file in your `package.json` with a `types` attribute

There is good documentation here: http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

And here is a live example (which I did in the past): https://github.com/caiogondim/logdown.js/pull/45/files

**Comment by balthazar** [comment]
This looks good then! Probably just call it `types.d.ts` and put it at the root of the project so it doesn't get confused with the actual source and the babel build

**Comment by balthazar** [comment]
Do you think we should keep this opened as long as everything is not typed for tracking purposes?

**Comment by bennyn** [comment]
Yes, let's keep it as a reminder. 😃

I can also make a list of the methods which are still missing definitions for tracking purposes.

**Reminder to myself**

Turn:

```ts
import Binance from 'binance-api-node'

const client: any = this.client = Binance({
  apiKey: process.env.BINANCE_API_KEY,
  apiSecret: process.env.BINANCE_API_SECRET,
})
```

Into:

```ts
import Binance, {BinanceClient} from 'binance-api-node'

const client: BinanceClient = this.client = Binance({
  apiKey: process.env.BINANCE_API_KEY,
  apiSecret: process.env.BINANCE_API_SECRET,
})
```

**Comment by balthazar** [comment]
Closing as https://github.com/binance-exchange/binance-api-node/pull/4. Improvements of typings will be expressed by new issues, thanks for your help @bennyn!

**Comment by bennyn** [comment]
@balthazar Okay! Looking forward we should consider using [tsd-jsdoc](https://github.com/dcodeIO/tsd-jsdoc). It would give us the ability to automatically generate type definitions from JSDoc comments. 😃
