### ISSUE TITLE
UserInfo Stream 400

### ISSUE THREAD

**Issue by John0x** [HyperCubeProject/binance-api-node#27]
Hey, I'm getting a 400 on the user info stream (https://stream.binance.com:9443/ws/.....).
code:
````
    this.userInfoFeed = await (this.api.client as any).ws.user((user) => {
      console.log(user);
    });
````

**Comment by balthazar** [comment]
Hey, are you sure this was not a server error? Are you logged successfully?

**Comment by John0x** [comment]
@balthazar I'm able to use the normal accountInfo call (without the websockets), so I guess I'm logged in successfully.
I'm using the library from within an chrome extension, but I don't think that's the problem, since the call is being made, it just gets a 400 from the binance server.

**Comment by balthazar** [comment]
And do you have a detailed error message?

**Comment by balthazar** [comment]
Feel free to reopen when you have more details.
