### ISSUE TITLE
Websocket request returns 400

### ISSUE THREAD

**Issue by nebsi04** [HyperCubeProject/binance-api-node#28]
I'm getting a 400 when trying to open a websocket. I'm using 
`client.ws.depth('ETHBTC', depth => {
  console.log(depth)
})` to test, but getting a 400 response. I tested the url it is creating with Simple Websocket Client. The wss:// protocol seems to be getting changed into https:// protocol somehow. In the Chrome Dev Tools I found the network request and it is "https://stream.binance.com:9443/ws/ethbtc@depth". So, in Simple Websocket Client extension I changed "https://" to "wss://" and it works. Just don't know how to fix it in this lib since it calls other dependencies that seem to be transforming the protocol and causing 400. Maybe I am doing something wrong.

**Comment by balthazar** [comment]
Are you sure this is not an API error at the time?

**Comment by nebsi04** [comment]
I'm pretty sure because I just used the ReactJS WebSocket component and it works now but doesn't work if I use binance-node-api.

**Comment by balthazar** [comment]
Even now? My depth websockets tests are passing so not sure what to say 🙁  Do you have more details of the error?

**Comment by nebsi04** [comment]
I was probably doing something wrong then. I'll try to reproduce this weekend. Thanks.

**Comment by balthazar** [comment]
Closing, reopen if you are able to provide a reprod.
