### ISSUE TITLE
No way to get historical trades

### ISSUE THREAD

**Issue by onedayitwillmake** [HyperCubeProject/binance-api-node#29]
Great library, I have a minor gripe.

It appears there is no way to get historical trade data.

There exist an command to access the `/trades` REST API point, but not `/historicalTrades` which accepts an additional `fromId` parameter which acts as a cursor / page-number

Relevant API documentation:
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#old-trade-lookup-market_data

**Comment by onedayitwillmake** [comment]
@balthazar Maybe it's useful information, maybe it's not - but I noticed when trying to work around this, that the only way to make the API calls work were to remove everything /except/ the API key. Removing the API key results in failure, as does adding anything in addition to the API key (no secret, no HMAC, no signature). 

```javascript
const signedRequest = function(url, data, callback) {
  let method = "GET";
  if ( !data ) data = {};
  let query = Object.keys(data).reduce(function(a,k){a.push(k+'='+encodeURIComponent(data[k]));return a},[]).join('&');
  let opt = {
    url: url+'?'+query,
    method: method,
    timeout: 60000,
    agent: false,
    headers: {
      'User-Agent': 'Mozilla/4.0 (compatible; Node Binance API)',
      'Content-type': 'application/x-www-form-urlencoded',
      'X-MBX-APIKEY': $API_KEY_GOES_HERE
    }
  };
  request(opt, function(error, response, body) {
    if ( !callback ) return;

    if ( error )
      return callback( error );

    if ( response && response.statusCode !== 200 )
      return callback( response );

    return callback( null, JSON.parse(body) );
  });
};


// Get historical trades
let options = {symbol: "ETHBTC", fromId: 12345678};
signedRequest(base + 'api/v1/historicalTrades', options, (error, data)=>{
  callback(error, data);
});
```

**Comment by balthazar** [comment]
Hum that's weird, the endpoint should behave the same way the others are doing. I've asked in the developer room without answer for now. Maybe it's still unstable
