### ISSUE TITLE
Determine what price a market order was executed at

### ISSUE THREAD

**Issue by sgtlambda** [HyperCubeProject/binance-api-node#31]
Hugely appreciate the work on this module, it's a fantastic way to interface with the binance API.

Is there a way to determine at what price a market order was executed without invoking the `myTrades` endpoint? It seems that `getOrder` always returns `0.000` for the `price` attribute in the case of a market order (which makes data-structure-wise given that it is a market order, it's just inconvenient for analytical purposes)

I gather that this question is probably more closely related to the actual workings of the API itself, rather than this specific client; but for future reference and documentation purposes it surely couldn't hurt to get a clear picture of how this would work.

**Comment by balthazar** [comment]
Hello, thanks!

Unfortunately I'm not doing anything special on my side, but this does look like a bug that should be forwarded to the Binance API telegram group

**Comment by sgtlambda** [comment]
Checked in with the Telegram group; adding the parameter `newOrderRespType: 'FULL',` to the order payload will, straight away, return a list of fills that made up the order.

Example:

```js
{ symbol: 'NEOETH',
  orderId: xxxxxxx,
  clientOrderId: 'xxxxxxx',
  transactTime: 1516591425646,
  price: '0.00000000',
  origQty: '0.20000000',
  executedQty: '0.20000000',
  status: 'FILLED',
  timeInForce: 'GTC',
  type: 'MARKET',
  side: 'BUY',
  fills: 
   [ { price: '0.12515000',
       qty: '0.20000000',
       commission: '0.00020000',
       commissionAsset: 'NEO',
       tradeId: xxxxxx } ] }
```

Want me to create a PR to add this to the docs?

**Comment by balthazar** [comment]
Nice, is it a parameter of `getOrder` too? I can only see it for the create order call, but if it works for `getOrder` I might set it by default to `FULL`
