### ISSUE TITLE
User Data Stream: listenKey keepAlive interval

### ISSUE THREAD

**Issue by jshkurti** [HyperCubeProject/binance-api-node#33]
https://github.com/HyperCubeProject/binance-api-node/blob/e54a26b0c2297c168841ef86d0b28c27296da3a2/src/websocket.js#L240

The official doc says : 

> Keepalive a user data stream to prevent a time out. User data streams will close after 60 minutes. It's recommended to send a ping about every 30 minutes.

Isn't it a bit too much to do it every 42 seconds ? :/

**Comment by balthazar** [comment]
Better be safe than sorry I would argue, you can't really predict network quality easily. I guess it could be bumped to 50, but where's the fun in that? 🙂
