### ISSUE TITLE
The documentation doesn't help setting up environment

### ISSUE THREAD

**Issue by adityamertia** [HyperCubeProject/binance-api-node#34]
I am unable to get the basic examples working. The documentation doesn't help setting up the basic environment.
Tried the @https://github.com/stefanpenner/es6-promise pollyfill but doesn't work. Are there steps to setup basic environment to run the examples?

**Comment by balthazar** [comment]
"Doesn't work" doesn't really help me understand your issue, you need to be more specific in your reporting. If you're talking about the `import` syntax, you either need to have a babel setup or do classic commonjs requires.

```js
const Binance = require('binance-api-node').default
```

**Comment by adityamertia** [comment]
Ok may be there has to be a mention of babel in the documentation. Even after above `const Binance = require('binance-api-node').default` i now get stuck in await not being recognized. If i install babel using `npm install --save-dev babel-cli babel-preset-env` how do i get it working with the example code?

**Comment by balthazar** [comment]
I'll add that to the readme, but all the babel is outside of the scope of this project. You'll need to document yourself on how to do it, or use the promise form as already explained in the readme 🙂
