### ISSUE TITLE
CORS issue with Public api call

### ISSUE THREAD

**Issue by rstims** [HyperCubeProject/binance-api-node#37]
Hello, when I make a public api call (ping, time or exchangeInfo, etc..) I receive a CORS error and the  logged error is 'TypeError: Failed to fetch'.  Not sure what Im doing wrong.  Im trying to avoid using API keys in this particular project.  Thank you.

**Comment by balthazar** [comment]
Hi, CORS are limitations imposed from the server. You will need to either ask the Binance developers on telegram if it's possible they implement them, or create a reverse proxy on your own. There is plenty of documentation on how to do that out there.

**Comment by SrBrahma** [comment]
At first, CORS blocked my api call in firefox. Tried in node REPL, worked. Found the following firefox extension: https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/ it works!

**Comment by SrBrahma** [comment]
Some function won't work with it (maybe will be edited to add more):

1) .accountSnapshot
