### ISSUE TITLE
Unhandled promise rejection when trying to clean user data stream websocket

### ISSUE THREAD

**Issue by jshkurti** [HyperCubeProject/binance-api-node#41]
Reproduce the issue with this code : 
```javascript
import Binance from 'binance-api-node';

const client = Binance({
  apiKey: 'Igj71woxxxxxxxxxxxxxxxxx',
  apiSecret: 'gkFWlxxxxxxxxxxxxxxxxx'
});

let clean;

setInterval(async () => {
  clean && clean();
  clean = await client.ws.user(() => {});
}, 5e3);
```

Once in a while (about 1 out of 5 times) the server responds with a 500 status code and this happens :
`(node:22103) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: An unknown error occured while processing the request.`

It comes from the closeDataStream call
https://github.com/HyperCubeProject/binance-api-node/blob/47c65c1e5cb8659b6e0f16ad49e6c882413aaa75/src/websocket.js#L245
and the exact unhandled promise rejection comes from here : 
https://github.com/HyperCubeProject/binance-api-node/blob/47c65c1e5cb8659b6e0f16ad49e6c882413aaa75/src/http.js#L21-L28

As a temporary workaround I just completely removed the closeDataStream() call since it seems it isn't really necessary. It turns out the server will return the same listenKey on getDataStream() call if it is still alive and you haven't deleted it.

**Comment by balthazar** [comment]
Heh, weird. Thanks for the easy reprod. I'm thinking of simply wrapping it in a `try catch` and simply do nothing in case of error, since as you said it doesn't matter much, what's your take?

**Comment by jshkurti** [comment]
Yeah just add a catch here : 
```javascript
const sendResult = call => 
   call.then(res => Promise.all([res, res.json()])).then(([res, json]) => { 
     if (!res.ok) { 
       throw new Error(json.msg || `${res.status} ${res.statusText}`) 
     } 
  
     return json 
   }).catch(console.error);
```
While it isn't really important for the `closeDataStream` case, it might be useful for the user to know when other HTTP requests fail.

**Comment by balthazar** [comment]
No I won't catch this one, otherwise users will be impacted. I just want to catch this useless `closeDataStream` error.

**Comment by jshkurti** [comment]
Ok then but keep in mind that try catch blocks do not prevent unhandled promise rejections.
I tried wrapping the `closeDataStream` call in a try catch, it still threw an unhandled promise rejection :/

**Comment by bennyn** [comment]
@jshkurti Can you please retry with v0.7.6 or above? Because we implemented reconnecting websockets.
