### ISSUE TITLE
Unhandled Promise Rejection when trying to establish a websocket connection (when cannot reach the Binance server)

### ISSUE THREAD

**Issue by RiyanshKarani011235** [HyperCubeProject/binance-api-node#44]
When the Node.js server (for some reason) cannot reach the Binance server, and you try opening a websocket (say for example `ws.depth`), the function call throws an `Unhandled Promise Rejection` leading to the Node.js server to crash. 

Looking at the [Websocket documentation](https://github.com/websockets/ws/blob/master/doc/ws.md) this happens when the event **error** is emitted by the underlying socket. Ideally, the function that tries to open a websocket should try and handle the **error** event by subscribing to the `websocket_instance.on("error", message => {...})` callback, which is missing in every function in the `websocket.js` module.

There is no way other than `process.on('uncaughtException', error => {...})` to catch such errors. In an ideal case, the functions in `websocket.js` should return a promise, that should be resolved only when the websocket connection is successfully established, or else should send a rejection. Something like below 

```js
const depth = (payload, cb) => {
  return new Promise((fulfill, reject) => {
    const cache = [];
    let count = 0;
    let payload = Array.isArray(payload) ? payload : [payload];
    (payload).forEach(symbol => {
      const w = new WebSocket(`${BASE}/${symbol.toLowerCase()}@depth`)
      cache.push(w);
      
      w.on('open', msg => {
        count++;
        if (count === payload.length) fulfill(() => cache.forEach(w => w.close()));
      });

      w.on('message', msg => {
        const {
          e: eventType,
          E: eventTime,
          s: symbol,
          u: finalUpdateId,
          U: firstUpdateId,
          b: bidDepth,
          a: askDepth,
        } = JSON.parse(msg)

        cb({
          eventType,
          eventTime,
          symbol,
          firstUpdateId,
          finalUpdateId,
          bidDepth: bidDepth.map(b => zip(['price', 'quantity'], b)),
          askDepth: askDepth.map(a => zip(['price', 'quantity'], a)),
        })
      });

      w.on('error', msg => {
        reject(msg);
      });
    })
  });
}
```

**Comment by bennyn** [comment]
@RiyanshKarani011235 Can you please retry with v0.7.6 or above? Because we implemented reconnecting websockets.
