### ISSUE TITLE
Compiled with 2 warnings [win 7 platform]

### ISSUE THREAD

**Issue by newbie78** [HyperCubeProject/binance-api-node#46]
i'm use vue-cli boilerplate (https://github.com/vuejs/vue-cli)
after vue init webpack client
a'm install the library:

- yarn add binance-api-node

- yarn run dev

 WARNING  Compiled with 2 warnings                                      17:

These dependencies were not found:

* bufferutil in ./node_modules/ws/lib/BufferUtil.js
* utf-8-validate in ./node_modules/ws/lib/Validation.js

To install them, you can run: npm install --save bufferutil utf-8-validate

- yarn add bufferutil utf-8-validate

- yarn run dev

 WARNING  Compiled with 2 warnings                                      17:49

 warning  in ./node_modules/bindings/bindings.js

81:22-40 Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/bindings/bindings.js

81:43-53 Critical dependency: the request of a dependency is an expression

how fix that error?

**Comment by newbie78** [comment]
it seems like the webpack conf trouble in vue-cli config (

**Comment by balthazar** [comment]
Seems like warnings more like errors, I only tried in a node environment, what happens if youstill try to call methods?

**Comment by balthazar** [comment]
Try version `0.7.0`, the problem should go away
