### ISSUE TITLE
clean() - Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by breitsmiley** [HyperCubeProject/binance-api-node#51]
In next example clean() function fired error

> (node:45) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined

```
const clean = client.ws.depth('ETHBTC', depth => {
  console.log(depth)
})

// After you're done
clean()
```

**Comment by breitsmiley** [comment]
This bug was fixed in release 0.5.6 in this [commit](https://github.com/HyperCubeProject/binance-api-node/commit/6655aae47b4cae5e6a5917276c491c319c783b44#diff-7cd41e7e5548228ba13f537ea2a76a20)  

But changes are not available after  npm install binance-api-node

**Comment by balthazar** [comment]
Publishing a new version

**Comment by balthazar** [comment]
Done in `0.5.7`
