### ISSUE TITLE
PURCHASE ERROR:  Error: Timestamp for this request is outside of the recvWindow.

### ISSUE THREAD

**Issue by jsappme** [HyperCubeProject/binance-api-node#65]
Any idea why this issue?
`
PURCHASE ERROR:  Error: Timestamp for this request is outside of the recvWindow.`

PS: I made sure my Windows time was updated

**Comment by balthazar** [comment]
Either wrong clock or bad network quality and the request lagged out. You can increase the `recvWindow` parameter if this is a connectivity issue you cannot improve so you don't get rejected.

**Comment by lookfirst** [comment]
Just a suggestion... put a nicer error message in there so that people don't have to come googling to find this issue. Thanks!

**Comment by acefxlabs** [comment]
The 

> Just a suggestion... put a nicer error message in there so that people don't have to come googling to find this issue. Thanks!

Its a response from Binance
