### ISSUE TITLE
Websocket handshake Error

### ISSUE THREAD

**Issue by JohnBDonner** [HyperCubeProject/binance-api-node#68]
I'm trying to use the websockets:
```js
const client = Binance()
const disconnect = client.ws.ticker('ETHBTC', ticker => {
  console.log(ticker)
})
```
and I'm running into some unexpected errors:

> WebSocket connection to 'wss://stream.binance.com:9443/ws/ethbtc@ticker' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received

Not sure how to go about fixing this, though I tried uninstalling `binance-api-node` and installing again. Using `npm` version `5.6.0` and `node` version `v9.4.0`.

**Comment by JohnBDonner** [comment]
Any thoughts on this @balthazar or @bennyn ?

**Comment by balthazar** [comment]
Hey, is this something which happens randomly or everytime you try to open this socket?

**Comment by JohnBDonner** [comment]
@balthazar  Unfortunately, this has happened every time I've tried connecting to a websocket channel on various occasions.

**Comment by bennyn** [comment]
I tested with this code and it works like a charm. So the bug is not reproducible for me. :-/

```js
const Binance = require('binance-api-node').default

const client = new Binance()

client.ws.ticker('ETHBTC', ticker => {
  console.log(ticker)
})
```

Which Binance API version are you using @JohnBDonner?

**Comment by JohnBDonner** [comment]
@bennyn here's from my `package-lock.json`:

```javascript
"binance-api-node": {
  "version": "0.7.4",
  "resolved": "https://registry.npmjs.org/binance-api-node/-/binance-api-node-0.7.4.tgz",
  "integrity": "sha512-NHsqnw3X+0koa5FHiaAepQE+SEZNH3OJ9H3WL8HZjapFw6BQNfowa8w7E5TAJVGsOL4vWf9UFuOs8xHfsZuk7w==",
  "requires": {
    "html5-websocket": "2.0.2",
    "isomorphic-fetch": "2.2.1",
    "lodash.zipobject": "4.1.3",
    "reconnecting-websocket": "3.2.2"
  }
}
```

**Comment by balthazar** [comment]
Using npm should not matter, it's most likely a connectivity issue on your side, or something is wrong with the binance certificate you have on your client.

**Comment by maxinminax** [comment]
I have same issue, It only came from when using on browser

**Comment by maxinminax** [comment]
I find the issue come from the package reconnecting-websocket, the Websocket was created with protocols NULL, so the header Sec-WebSocket-Protocol was send as NULL

> https://github.com/pladaria/reconnecting-websocket/blob/master/index.ts#L153

>

**Comment by balthazar** [comment]
`0.7.6` release published, closing
