### ISSUE TITLE
Strategy to avoid "INVALID_TIMESTAMP"

### ISSUE THREAD

**Issue by bennyn** [HyperCubeProject/binance-api-node#80]
Binance is pretty strict about the timestamp which is sent to the server on every request.

To avoid the "Request used an outdated timestamp" error, we could sync our own time with an online atomic clock service to determine our clock drift (which can then be used to adjust the timestamps).

**Comment by balthazar** [comment]
Isn't the `useServerTime` option supposed to solve this issue?

**Comment by bennyn** [comment]
@balthazar Good point! Haven't checked this one. 🙈

I was already investigating on how to determine the local clock drift by using [Sntp](https://github.com/hueniverse/sntp). My idea was to detect the offset in milliseconds to then add it to all locally created timestamps:

```js
const Sntp = require('sntp');

Sntp.time({
  host: 'pool.ntp.org',
  port: 123,
  resolveReference: true,
  timeout: 1000
})
.then((time) => {
  const offset = parseInt(time.t, 10);
  const timestamp = Date.now() + offset;
  console.log(`Offset: ${offset}ms`);
  console.log(`Adjusted timestamp: ${timestamp}`);
});
```

I will test the `useServerTime` option tonight and report back later!

**Comment by balthazar** [comment]
Using sntp might worsen the compatibility of the library in the browser, which I think is still not ideal as someone using webpack previously reported.

I think the param is the way to go, but maybe it would be better to have it at the client level rather than a per-call basis

**Comment by bennyn** [comment]
I just had another idea... 

Would it be possible to send the time offset already with the `constructor`?

**Code:**

```js
const Binance = require('binance-api-node').default

const client = Binance({
  apiKey: process.env.BINANCE_API_KEY,
  apiSecret: process.env.BINANCE_API_SECRET,
  clockDrift: -2200 // 2200ms in the past
});
```

**Comment by bennyn** [comment]
Ok, I am fine with that as long as it is possible to update the clock drift during runtime. Can you please make a code proposal so that I can work on implementing that?

**Comment by bennyn** [comment]
@balthazar What was the reason that `useServerTime` has been only implemented for signed endpoints? I would need it also to query public endpoints like [prices](https://github.com/HyperCubeProject/binance-api-node#prices). If this could be done, that would be perfect!

We could also make `useServerTime` to accept a `boolean` value or a `function`. Boolean value would turn on to query the server time from Binance and a function would act as callback parameter that could be use for custom time updates. What do you think?

**Comment by balthazar** [comment]
I tried  to specify a timestamp for public endpoints at some points and hit some weird issue, which was probably something else and thought that providing a timestamp was not available for public ones. If this is untrue, we can add it to public endpoints too.

I'm not really confident with having this confusing API, I would prefer having another parameter for the custom `getTime` function

**Comment by bennyn** [comment]
Hey @balthazar, it has been some time and I would really like to be able to pass a function to "binance-api-node" which is used to calculate the "timestamp" which is sent to Binance. 

What would be the easiest to achieve this? Can you give me some pseudo code to point me in the correct direction?

**Comment by balthazar** [comment]
You would pass a `getTime` to the opts along with the `apiKey` that would return the time. Before that could you make sure that public endpoints do accept the `timestamp` extra parameter?

**Comment by ManuCart** [comment]
Any news about this issue?
Have this error sometimes
````
(node:814) UnhandledPromiseRejectionWarning: Error: Timestamp for this request was 1000ms ahead of the server's time.
````

**Comment by balthazar** [comment]
Closing thanks to #162
