### ISSUE TITLE
Error: Account has insufficient balance for requested action

### ISSUE THREAD

**Issue by rodrigooler** [HyperCubeProject/binance-api-node#81]
I am getting error "Error: Account has insufficient balance for requested action" when executing the order function, below is the implemented code example.

```javascript
import Binance from 'binance-api-node'

const SIDE_OPTIONS = {
  BUY: 'BUY',
  SELL: 'SELL',
};

function runBinance(apiKey, apiSecret) {
  return new Binance({
    apiKey,
    apiSecret,
    useServerTime: true, // If you get timestamp errors, synchronize to server time at startup
    test: true, // If you want to use sandbox mode where orders are simulated
  });
}

export async function buyOrder(
  binanceApiKey,
  binanceApiSecret,
  symbol,
  quantity,
  price,
  type,
) {
  try {
    await runBinance(binanceApiKey, binanceApiSecret)
      .order({
        symbol,
        side: SIDE_OPTIONS.BUY,
        quantity,
        type,
        price,
      });

    return;
  } catch (error) {
    return {
      error: {
        status: 400,
        message: error,
      }
    }
  }
}
```

Can anyone tell me if the test flag is working anyway? I do not want to use resources from my wallet for now.

**Comment by bennyn** [comment]
@rodrigooler Please try with `client.orderTest` instead of using `client.order`.

Here is an example:
- https://github.com/HyperCubeProject/binance-api-node/blob/0.7.4/test/authenticated.js#L13

**Comment by balthazar** [comment]
There is no `test` flag, you confused the client construction with the other lib.

It should only be 

```js
function runBinance(apiKey, apiSecret) {
  return Binance({
    apiKey,
    apiSecret,
  });
}
```

And as @bennyn said, use the `orderTest` method

**Comment by rodrigooler** [comment]
@bennyn @balthazar thank you, I had settled here but forgot to close the issue. But reinforcing again thanks for the reply!

**Comment by rodrigooler** [comment]
@FredMichel you must use the order Test. 

```js
console.log(await client.orderTest({
  symbol: 'XLMETH',
  side: 'BUY',
  quantity: 100,
  price: 0.0002,
}))
```

https://github.com/HyperCubeProject/binance-api-node/tree/0.7.4#ordertest
https://github.com/HyperCubeProject/binance-api-node/blob/0.7.4/test/authenticated.js#L13
