### ISSUE TITLE
ERROR: TIMESTAMP FOR THIS REQUEST WAS 1000MS AHEAD OF THE SERVER'S TIME.

### ISSUE THREAD

**Issue by rodrigooler** [HyperCubeProject/binance-api-node#87]
I'm getting the following error when placing a purchase order
```
ERROR: TIMESTAMP FOR THIS REQUEST WAS 1000MS AHEAD OF THE SERVER'S TIME.
```

```javascript
  return new Binance({
    apiKey,
    apiSecret,
    useServerTime: true, // It should solve the above problem.
  });
```

Has anyone had this problem while using it in production? In tests everything is OK, but when I change orderTest to order the above error occurs.

Sending data to my server running:
```data
{
	"symbol": "LTCETH",
	"quantity": 0.00190000,
	"userId": "5ac9c2ad41a43a3770beb263"
}
```

**Comment by balthazar** [comment]
You're using the wrong library, we don't use classes.

**Comment by rodrigooler** [comment]
@balthazar thanks, I just noticed "new" because I was using another library ... really a stupid mistake!

**Comment by balthazar** [comment]
It happens, have a good one! 🙂

**Comment by rodrigooler** [comment]
Thank you, have a great day! 🙂

**Comment by Evrard20** [comment]
const Binance = require('binance-api-node').default;
	const client = Binance();
	const client2 = Binance({
		apiKey: 
	  	apiSecret: 
	    useServerTime: true,
	})
 Im still getting this timestamp error after using this code

**Comment by denimar** [comment]
@Evrard20  it is because the property useServerTime doen't exist in the library "binance-api-node"
