### ISSUE TITLE
Prices using Websockets

### ISSUE THREAD

**Issue by ammichael** [HyperCubeProject/binance-api-node#96]
Hi there!

First I want to thank you for your awesome wrapper. It really spared me (and others) tons of work. 😬

I may be missing something, but how can I get symbol's latest prices using websockets? I'm able to use websocket to get tickers and candles, but how about the price?

Thanks.

**Comment by balthazar** [comment]
Hey, thanks for your message! 🙂 

You can either listen to the trade websocket of a symbol and look at the price executed, or listen to candles with a 1m interval and look at the close price.

**Comment by balthazar** [comment]
A trade is when something is traded 😛

**Comment by ammichael** [comment]
Makes sense 😂
The price varies so much per trade that I really thought it was open orders too. Well, I'm going to use candles with 1m interval.

Thanks a lot!
